name: gh_runner
on: workflow_dispatch

jobs:
  test-model:
    name: Do the job on the runner
    runs-on: ubuntu-latest 
    steps:
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug-report.yml # optional but recommended
    
      - run: cat ${HOME}/issue-parser-result.json
      
      - run: echo $FAVORITE_DISH
        env:
          FAVORITE_DISH: ${{ steps.issue-parser.outputs.issueparser_favorite_dish }}

      # Install datalad 🟢
      - name: Install Datalad
        run: |
          sudo apt-get install datalad
          python3 -m pip install datalad-osf
          git config --global user.name "trained_models"
          git config --global user.email "trained_models"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          datalad siblings
          datalad siblings
          cd PialNN/pialnn/1.0.0/data
          datalad get sample.zip
          find . -name "*.zip" -exec unzip {} \;
          mv example example_gh
          datalad save -m "pushing unzipped folder" example_gh/
          datalad push -f all --to test-aws-storage
          datalad push --to origin
 