name: osf_test
on: workflow_dispatch

jobs:
   create_new_branch:
     runs-on: ubuntu-latest

     steps:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: 3.11

     - name: Install datalad and datalad-osf
       uses: datalad/datalad-action/install@main
       with:
         pip_install: datalad-osf 

     - name: Setting git credentials
       run: |
        git config --global user.name "hvgazula"
        git config --global user.email "hvgazula@umich.edu"

     - name: Checkout the repo
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Git-annex/Datalad add the weights
       env:
         OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
       run: |
        datalad download-url -o -m "Added cortex weights" https://neuronets.github.io/cortexode-forked/ckpts.zip
        datalad push --to test-aws-storage
        datalad push --to origin

     - name: Git-annex/Datalad add the sample datasets
       run: |
        cd PialNN/pialnn/1.0.0/data

        datalad get sample.zip
        find . -name "*.zip" -exec unzip {} \;
        mv example example_test1
        
        datalad save -m "pushing unzipped folder" example_test1/
        datalad push -f all --to test-aws-storage
        datalad push --to origin
