name: osf_test
on: workflow_dispatch
permissions: write-all

jobs:
   create_new_branch:
     runs-on: ubuntu-latest

     steps:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: 3.11

     - name: Install Datalad
       id: testing
       run: |
        sudo apt-get install datalad
        python3 -m pip install datalad-osf
        pip install requests
        git config --global user.name "hvgazula"
        git config --global user.email "hvgazula@umich.edu"

     - name: Checkout the repo
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     - name: Git-annex/Datalad add the weights
       env:
         OSF_TOKEN: ${{ secrets.OSF_TOKEN }}
       run: |
        datalad siblings
        datalad download-url -m "Added cortex weights" https://neuronets.github.io/cortexode-forked/ckpts.zip
        datalad push --to test-aws-storage
        datalad push --to origin